Fixed some CI steps, extended the preparations for later unittests

diff --git a/.github/workflows/python3.yml b/.github/workflows/python3.yml
--- a/.github/workflows/python3.yml
+++ b/.github/workflows/python3.yml
@@ -17,24 +17,26 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
+    - name: Install dependencies and setup the environment
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest pylint build
+        sudo apt install python3-dev python3-venv default-libmysqlclient-dev build-essential -y
+        python3 -m pip install --upgrade pip
+        pip install flake8 pytest pylint build pymysql mysqlclient cryptography
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        sudo systemctl start mysql.service
     - name: Lint with flake8
       run: |
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
     - name: Lint with PyLint
       run: |
-        python -c 'import subprocess; subprocess.run("pylint matebot_core/ -j 0".split(" "));'
+        pylint matebot_core/ -j 0 && echo "OK" || echo "FAIL"
     - name: Build docs using Sphinx
       run: |
         cd docs
         pip install -r requirements.txt
         make html
-    - name: Run matebot_core unittests
+    - name: Run matebot_core unittests with temporary sqlite3
       run: |
         python3 -m unittest tests -v
     - name: Run matebot_core once
